In [3]:
import pandas as pd
from IPython.display import display

file_path = r"C:\Users\vaibh\OneDrive\Desktop\Projects\ETL_Healthcare_Project\healthcare_dataset.xlsx"

df = pd.read_excel(file_path)

In [4]:
display(df.head(10))

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28131,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.32729,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.09608,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78241,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.31781,458,Urgent,2022-10-09,Penicillin,Abnormal
5,Emily Johnson,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.11095,389,Urgent,2023-12-24,Ibuprofen,Normal
6,Edward Edwards,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.87234,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,Christina Martinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.46272,277,Emergency,2022-01-07,Paracetamol,Inconclusive
8,Jasmine Aguilar,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.22279,316,Elective,2020-07-14,Aspirin,Abnormal
9,Christopher Berg,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.63106,249,Elective,2021-06-22,Paracetamol,Inconclusive

In [5]:
# ==========================================
# DATA PROFILING
# ==========================================

from IPython.display import display

display(pd.DataFrame({
    "Rows": [df.shape[0]],
    "Columns": [df.shape[1]]
}))

    Rows  Columns
0  55500       15

In [7]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  datetime64[ns]
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.4+ MB

None

In [8]:
duplicates = df[df.duplicated()]

display(duplicates)

display(
    pd.DataFrame({
        "Total Duplicate Rows": [df.duplicated().sum()]
    })
)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
50023,Samuel Joyce,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830590,157,Urgent,2022-11-22,Aspirin,Inconclusive
50040,Kimberly Vasquez,26,Male,A-,Obesity,2023-10-23,Jennifer Bennett,Cowan Inc,UnitedHealthcare,38142.109680,313,Urgent,2023-11-18,Penicillin,Abnormal
50055,Scott Thornton,55,Female,B-,Obesity,2021-04-08,Joshua Ingram,Keller LLC,Medicare,30894.904510,455,Urgent,2021-04-15,Aspirin,Abnormal
50070,William Lee,27,Female,O+,Arthritis,2020-01-31,Lauren Montgomery,Winters-Simon,Cigna,46229.434900,153,Elective,2020-02-13,Lipitor,Normal
50078,Christopher Norris,38,Male,AB-,Arthritis,2023-01-14,Denise Blair,Inc Morales,Medicare,9072.127142,452,Emergency,2023-02-12,Penicillin,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55461,Connor Compton,63,Male,A+,Asthma,2021-08-21,Jonathan Allen,"and Willis Mullins, Bowers",Medicare,1936.702824,375,Emergency,2021-09-16,Paracetamol,Normal
55462,Alyssa Miller,35,Female,A-,Diabetes,2022-06-30,Ryan Price,Shelton-Gallagher,UnitedHealthcare,2210.460898,289,Elective,2022-07-27,Penicillin,Normal
55464,Chris Hughes,35,Female,AB-,Obesity,2024-02-28,Katelyn Perry,Lyons-Hansen,Blue Cross,11889.154510,128,Emergency,2024-03-14,Paracetamol,Abnormal
55484,Kenneth Alvarez,80,Male,O+,Cancer,2022-05-05,Andrew Conner,Sons Mayo and,Cigna,45653.802310,114,Elective,2022-05-17,Aspirin,Normal
55491,Linda Griffin,47,Female,O+,Obesity,2020-06-21,Danielle Davis,"and King Jordan Johnson,",Aetna,15715.551080,310,Emergency,2020-06-25,Lipitor,Abnormal

   Total Duplicate Rows
0                   534

In [9]:
duplicate_rows = df[df.duplicated(keep=False)]

display(duplicate_rows)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
64,Nancy Glover,58,Male,A-,Hypertension,2020-05-08,Jennifer Larson,"Khan, and Rodriguez Fischer",Medicare,19183.168890,378,Emergency,2020-06-01,Aspirin,Abnormal
107,David Higgins,49,Female,B-,Arthritis,2021-03-05,Erin Henderson MD,"Evans and Hall Schneider,",Medicare,24948.477820,361,Emergency,2021-03-20,Penicillin,Abnormal
148,Robert Higgins,42,Male,AB-,Asthma,2021-05-06,Scott Davis,"and Ford Lee, Rodriguez",Medicare,13355.782090,451,Elective,2021-05-29,Ibuprofen,Inconclusive
154,Kevin Hicks,66,Male,AB+,Arthritis,2021-06-23,Kelly Murphy,Robinson Inc,Medicare,1897.891727,196,Elective,2021-07-09,Ibuprofen,Abnormal
159,Michael Taylor,29,Male,O-,Asthma,2020-02-27,Erica Mccormick,Donaldson-Frey,Medicare,41939.119940,453,Elective,2020-03-26,Ibuprofen,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55461,Connor Compton,63,Male,A+,Asthma,2021-08-21,Jonathan Allen,"and Willis Mullins, Bowers",Medicare,1936.702824,375,Emergency,2021-09-16,Paracetamol,Normal
55462,Alyssa Miller,35,Female,A-,Diabetes,2022-06-30,Ryan Price,Shelton-Gallagher,UnitedHealthcare,2210.460898,289,Elective,2022-07-27,Penicillin,Normal
55464,Chris Hughes,35,Female,AB-,Obesity,2024-02-28,Katelyn Perry,Lyons-Hansen,Blue Cross,11889.154510,128,Emergency,2024-03-14,Paracetamol,Abnormal
55484,Kenneth Alvarez,80,Male,O+,Cancer,2022-05-05,Andrew Conner,Sons Mayo and,Cigna,45653.802310,114,Elective,2022-05-17,Aspirin,Normal
55491,Linda Griffin,47,Female,O+,Obesity,2020-06-21,Danielle Davis,"and King Jordan Johnson,",Aetna,15715.551080,310,Emergency,2020-06-25,Lipitor,Abnormal

In [10]:
rows_before = len(df)

display(
    pd.DataFrame({
        "Rows Before": [rows_before]
    })
)

   Rows Before
0        55500

In [11]:
df = df.drop_duplicates()

In [12]:
rows_after = len(df)

display(
    pd.DataFrame({
        "Rows Before": [rows_before],
        "Rows After": [rows_after],
        "Duplicates Removed": [rows_before - rows_after],
        "Duplicates Remaining": [df.duplicated().sum()]
    })
)

   Rows Before  Rows After  Duplicates Removed  Duplicates Remaining
0        55500       54966                 534                     0

In [13]:
# ==========================================
# VALIDATE DUPLICATE REMOVAL
# ==========================================

validation = pd.DataFrame({
    "Validation Check": [
        "Duplicate Records Remaining",
        "Rows After Cleaning"
    ],
    "Result": [
        df.duplicated().sum(),
        len(df)
    ]
})

display(validation)

              Validation Check  Result
0  Duplicate Records Remaining       0
1          Rows After Cleaning   54966

In [28]:
# ==========================================
# FEATURE ENGINEERING
# Create new columns for analysis
# ==========================================

# ------------------------------------------------
# 1. Calculate Length of Stay (in days)
# ------------------------------------------------
df["Length_of_Stay"] = (
    df["Discharge Date"] -
    df["Date of Admission"]
).dt.days

# ------------------------------------------------
# 2. Create Age Groups
# ------------------------------------------------
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0, 18, 35, 50, 65, 100],
    labels=[
        "Child",
        "Young Adult",
        "Adult",
        "Senior",
        "Elderly"
    ]
)

# ------------------------------------------------
# 3. Create Billing Category
# ------------------------------------------------
df["Billing_Category"] = pd.qcut(
    df["Billing Amount"],
    q=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

# ------------------------------------------------
# 4. Create Admission Date Features
# ------------------------------------------------
df["Admission_Year"] = df["Date of Admission"].dt.year
df["Admission_Month"] = df["Date of Admission"].dt.month_name()
df["Admission_Day"] = df["Date of Admission"].dt.day

# ------------------------------------------------
# 5. Create Discharge Date Features
# ------------------------------------------------
df["Discharge_Year"] = df["Discharge Date"].dt.year
df["Discharge_Month"] = df["Discharge Date"].dt.month_name()

# ------------------------------------------------
# 6. Create Stay Category
# ------------------------------------------------
df["Stay_Category"] = pd.cut(
    df["Length_of_Stay"],
    bins=[0, 5, 10, 20, 100],
    labels=[
        "Short Stay",
        "Medium Stay",
        "Long Stay",
        "Extended Stay"
    ]
)

# ==========================================
# Display newly created columns
# ==========================================

display(
    df[[
        "Age",
        "Age_Group",
        "Billing Amount",
        "Billing_Category",
        "Length_of_Stay",
        "Stay_Category",
        "Admission_Year",
        "Admission_Month",
        "Admission_Day",
        "Discharge_Year",
        "Discharge_Month"
    ]].head(10)
)

# ==========================================
# Display total rows and columns
# ==========================================

display(
    pd.DataFrame({
        "Total Rows": [len(df)],
        "Total Columns": [len(df.columns)]
    })
)

,Age,Age_Group,Billing Amount,Billing_Category,Length_of_Stay,Stay_Category,Admission_Year,Admission_Month,Admission_Day,Discharge_Year,Discharge_Month
0,30,Young Adult,18856.28131,Medium,2,Short Stay,2024,January,31,2024,February
1,62,Senior,33643.32729,High,6,Medium Stay,2019,August,20,2019,August
2,76,Elderly,27955.09608,High,15,Long Stay,2022,September,22,2022,October
3,28,Young Adult,37909.78241,Very High,30,Extended Stay,2020,November,18,2020,December
4,43,Adult,14238.31781,Medium,20,Long Stay,2022,September,19,2022,October
5,36,Adult,48145.11095,Very High,4,Short Stay,2023,December,20,2023,December
6,21,Young Adult,19580.87234,Medium,12,Long Stay,2020,November,3,2020,November
7,20,Young Adult,45820.46272,Very High,10,Medium Stay,2021,December,28,2022,January
8,82,Elderly,50119.22279,Very High,13,Long Stay,2020,July,1,2020,July
9,58,Senior,19784.63106,Medium,30,Extended Stay,2021,May,23,2021,June

   Total Rows  Total Columns
0       54966             24

In [29]:
# ==========================================
# DATA VALIDATION
# Validate the transformed dataset
# ==========================================

from IPython.display import display

# ------------------------------------------
# Missing Values
# ------------------------------------------
missing_values = df.isnull().sum().sum()

# ------------------------------------------
# Duplicate Records
# ------------------------------------------
duplicate_records = df.duplicated().sum()

# ------------------------------------------
# Negative Age
# ------------------------------------------
negative_age = (df["Age"] < 0).sum()

# ------------------------------------------
# Negative Billing Amount
# ------------------------------------------
negative_billing = (df["Billing Amount"] < 0).sum()

# ------------------------------------------
# Negative Length of Stay
# ------------------------------------------
negative_stay = (df["Length_of_Stay"] < 0).sum()

# ------------------------------------------
# Invalid Date Records
# (Discharge Date before Admission Date)
# ------------------------------------------
invalid_dates = (
    df["Discharge Date"] <
    df["Date of Admission"]
).sum()

# ------------------------------------------
# Display Validation Summary
# ------------------------------------------
validation_report = pd.DataFrame({
    "Validation Check": [
        "Missing Values",
        "Duplicate Records",
        "Negative Age",
        "Negative Billing Amount",
        "Negative Length of Stay",
        "Invalid Dates"
    ],
    "Result": [
        missing_values,
        duplicate_records,
        negative_age,
        negative_billing,
        negative_stay,
        invalid_dates
    ],
    "Status": [
        "Pass" if missing_values == 0 else "Fail",
        "Pass" if duplicate_records == 0 else "Fail",
        "Pass" if negative_age == 0 else "Fail",
        "Pass" if negative_billing == 0 else "Fail",
        "Pass" if negative_stay == 0 else "Fail",
        "Pass" if invalid_dates == 0 else "Fail"
    ]
})

display(validation_report)

          Validation Check  Result Status
0           Missing Values       0   Pass
1        Duplicate Records       0   Pass
2             Negative Age       0   Pass
3  Negative Billing Amount     106   Fail
4  Negative Length of Stay       0   Pass
5            Invalid Dates       0   Pass

In [30]:
# ==========================================
# INSPECT NEGATIVE BILLING AMOUNTS
# ==========================================

negative_billing_records = df[df["Billing Amount"] < 0]

display(negative_billing_records)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,...,Test Results,Length_of_Stay,Age_Group,Billing_Category,Admission_Year,Admission_Month,Admission_Day,Discharge_Year,Discharge_Month,Stay_Category
132,Ashley Erickson,32,Female,AB-,Cancer,2019-11-05,Gerald Hooper,"and Johnson Moore, Branch",Aetna,-502.507813,...,Normal,18,Young Adult,Low,2019,November,5,2019,November,Long Stay
799,Christopher Weiss,49,Female,AB-,Asthma,2023-02-16,Kelly Thompson,Hunter-Hughes,Aetna,-1018.245371,...,Inconclusive,21,Adult,Low,2023,February,16,2023,March,Extended Stay
1018,Ashley Warner,60,Male,A+,Hypertension,2021-12-21,Andrea Bentley,"and Wagner, Lee Klein",Aetna,-306.364925,...,Normal,21,Senior,Low,2021,December,21,2022,January,Extended Stay
1421,Jay Galloway,74,Female,O+,Asthma,2021-01-20,Debra Everett,Group Peters,Blue Cross,-109.097122,...,Abnormal,20,Elderly,Low,2021,January,20,2021,February,Long Stay
2103,Joshua Williamson,72,Female,B-,Diabetes,2021-03-21,Wendy Ramos,"and Huff Reeves, Dennis",Blue Cross,-576.727907,...,Abnormal,27,Elderly,Low,2021,March,21,2021,April,Extended Stay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52213,Mr. Christopher Alvarado,74,Male,AB+,Obesity,2022-06-03,Mr. Dean Guzman DDS,Johnson Inc,Blue Cross,-1310.272895,...,Inconclusive,10,Elderly,Low,2022,June,3,2022,June,Medium Stay
52629,Gabrielle Decker,66,Male,AB-,Arthritis,2022-11-07,William Krause,Diaz-Bishop,Cigna,-676.852502,...,Normal,23,Elderly,Low,2022,November,7,2022,November,Extended Stay
53204,Ashley Warner,55,Male,A+,Hypertension,2021-12-21,Andrea Bentley,"and Wagner, Lee Klein",Aetna,-306.364925,...,Normal,21,Senior,Low,2021,December,21,2022,January,Extended Stay
53232,Daniel Drake,68,Female,B+,Hypertension,2020-04-24,Brett Ray,Carr Ltd,Aetna,-591.917419,...,Abnormal,2,Elderly,Low,2020,April,24,2020,April,Short Stay
54136,Dr. Michael Mckay,64,Male,O+,Cancer,2019-05-31,Dawn Navarro,"Mcconnell and Rios, Clark",UnitedHealthcare,-199.663794,...,Abnormal,12,Senior,Low,2019,May,31,2019,June,Long Stay

In [31]:
# ==========================================
# FLAG NEGATIVE BILLING RECORDS
# ==========================================

df["Negative_Billing_Flag"] = df["Billing Amount"] < 0

display(
    df[[
        "Billing Amount",
        "Negative_Billing_Flag"
    ]].head(10)
)

   Billing Amount  Negative_Billing_Flag
0     18856.28131                  False
1     33643.32729                  False
2     27955.09608                  False
3     37909.78241                  False
4     14238.31781                  False
5     48145.11095                  False
6     19580.87234                  False
7     45820.46272                  False
8     50119.22279                  False
9     19784.63106                  False

In [32]:
# ==========================================
# UPDATE VALIDATION REPORT
# ==========================================

missing_values = df.isnull().sum().sum()
duplicate_records = df.duplicated().sum()
negative_age = (df["Age"] < 0).sum()
negative_billing = (df["Billing Amount"] < 0).sum()
negative_stay = (df["Length_of_Stay"] < 0).sum()
invalid_dates = (
    df["Discharge Date"] <
    df["Date of Admission"]
).sum()

validation_report = pd.DataFrame({
    "Validation Check": [
        "Missing Values",
        "Duplicate Records",
        "Negative Age",
        "Negative Billing Amount",
        "Negative Length of Stay",
        "Invalid Dates"
    ],
    "Result": [
        missing_values,
        duplicate_records,
        negative_age,
        negative_billing,
        negative_stay,
        invalid_dates
    ],
    "Status": [
        "Pass" if missing_values == 0 else "Fail",
        "Pass" if duplicate_records == 0 else "Fail",
        "Pass" if negative_age == 0 else "Fail",
        "Review" if negative_billing > 0 else "Pass",
        "Pass" if negative_stay == 0 else "Fail",
        "Pass" if invalid_dates == 0 else "Fail"
    ]
})

display(validation_report)

          Validation Check  Result  Status
0           Missing Values       0    Pass
1        Duplicate Records       0    Pass
2             Negative Age       0    Pass
3  Negative Billing Amount     106  Review
4  Negative Length of Stay       0    Pass
5            Invalid Dates       0    Pass

In [34]:
# ==========================================
# CREATE ETL LOG
# ==========================================

etl_log = pd.DataFrame({
    "Step": [
        "Extract",
        "Data Profiling",
        "Remove Duplicates",
        "Feature Engineering",
        "Data Validation"
    ],

    "Description": [
        "Loaded healthcare dataset from Excel",
        "Performed data profiling and quality assessment",
        "Removed duplicate records",
        "Created derived columns for analysis",
        "Validated transformed dataset"
    ],

    "Rows Affected": [
        55500,
        55500,
        534,
        len(df),
        len(df)
    ],

    "Status": [
        "Completed",
        "Completed",
        "Completed",
        "Completed",
        "Completed"
    ]
})

display(etl_log)

,Step,Description,Rows Affected,Status
0,Extract,Loaded healthcare dataset from Excel,55500,Completed
1,Data Profiling,Performed data profiling and quality assessment,55500,Completed
2,Remove Duplicates,Removed duplicate records,534,Completed
3,Feature Engineering,Created derived columns for analysis,54966,Completed
4,Data Validation,Validated transformed dataset,54966,Completed

In [37]:
# ==========================================
# LOAD
# Save transformed dataset
# ==========================================

# Save as Excel
df.to_excel("healthcare_cleaned.xlsx", index=False)

# Save as CSV
df.to_csv("healthcare_cleaned.csv", index=False)

# Save ETL Log
etl_log.to_excel("etl_log.xlsx", index=False)

display(
    pd.DataFrame({
        "File Name": [
            "healthcare_cleaned.xlsx",
            "healthcare_cleaned.csv",
            "etl_log.xlsx"
        ],
        "Status": [
            "Saved Successfully",
            "Saved Successfully",
            "Saved Successfully"
        ]
    })
)

                 File Name              Status
0  healthcare_cleaned.xlsx  Saved Successfully
1   healthcare_cleaned.csv  Saved Successfully
2             etl_log.xlsx  Saved Successfully

In [38]:
# ==========================================
# SAVE DATASET + ETL LOG IN THE SAME EXCEL FILE
# ==========================================

file_path = r"C:\Users\vaibh\OneDrive\Desktop\Projects\ETL_Healthcare_Project\healthcare_dataset.xlsx"

with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Healthcare_Data", index=False)
    etl_log.to_excel(writer, sheet_name="ETL_Log", index=False)

display(
    pd.DataFrame({
        "Workbook": ["healthcare_dataset.xlsx"],
        "Sheets": ["Healthcare_Data, ETL_Log"],
        "Status": ["Updated Successfully"]
    })
)

                  Workbook                    Sheets                Status
0  healthcare_dataset.xlsx  Healthcare_Data, ETL_Log  Updated Successfully